apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-fe
  namespace: emojichat # {"$kpt-set":"namespace"}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-fe
  template:
    metadata:
      labels:
        app: chatbot-fe
    spec:
      # TODO(jlewi): Should add a health check
      containers:
      - name: fe
        image: gcr.io/issue-label-bot-dev/chatbot-fe:2209314-dirty@sha256:b8c73274dfab0ec755edf4021cc90a242b3fd85f6f3fe2b5db21400fb886b293 # {"$kpt-set":"image"}
        command:
        - /server
        - serve
        # ISTIO binds port 80
        - --port=8080
        - --static-files=/static
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
      serviceAccountName: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
  namespace: emojichat # {"$kpt-set":"namespace"}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      # TODO(jlewi): Should add a health check
      containers:
      - name: fe
        image: gcr.io/issue-label-bot-dev/jl-rasa:83da840-dirty@sha256:24df139fcd6b218039ff0a861666736942942bc9debc7190483de16de83722b9 # {"$kpt-set":"image-rasa"}
        command:
        - rasa
        - run
        # TODO(jlewi): Should we move the rasa log onto a PD? Is there anyreason to use a log file? Should
        # we just emit to stdout/stderr and collect the logs?
        - --log-file=/tmp/rasa.log
        - --cors="*"
        # TODO(jlewi): What are good resource limits      
        resources:
          requests:
            memory: "8Gi"
            cpu: "8"
      serviceAccountName: default
