apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: issue-label-bot-user@issue-label-bot-dev.iam.gserviceaccount.com
  name: default-editor
  namespace: emojichat # {"$kpt-set":"namespace"}
