apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # TODO(jlewi): Need to create a kpt setter for this.
  name: workspace-jl-rasa # {"$kpt-set":"pvc-name"}
  namespace: label-bot-dev # {"$kpt-set":"namespace"}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # We need more storage.
      storage: 100Gi
  storageClassName: standard
  volumeMode: Filesystem
