# Reference: https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: chatbot # {"$kpt-set":"name"}
build:
  artifacts:
  - image: gcr.io/issue-label-bot-dev/chatbot-fe # {"$kpt-set":"image-notag"}
    # All paths in the dockerfile should be relative to this
    context: .
    kaniko:
      # Relative to context
      dockerfile: Dockerfile
      buildContext:
        gcsBucket: issue-label-bot-dev_skaffold-kaniko
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS # TODO(GoogleContainerTools/skaffold#3468) skaffold doesn't
        value: /secret/user-gcp-sa.json
      cache: {}
  cluster:
    pullSecretName: user-gcp-sa
    # Build in the kaniko namespace because we need to disable ISTIO sidecar injection
    # see  GoogleContainerTools/skaffold#3442
    namespace: kaniko
    resources:
      requests:
        cpu: 8
        memory: 16Gi
deploy:
  kustomize:
    path: .
